apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-node-shutdown.fullname" . }}
rules:
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
