---
{{ if .Values.persistence.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "rdt-client.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-db
spec:
  accessModes:
  - {{ .Values.persistence.db.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
  storageClassName: {{ .Values.persistence.db.storageClassname }}
{{ end }}
