replicaCount: 1

image:
  registry: docker.io
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: 2.0.39

# -- Set custom environment variables
environment: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

persistence:
  downloads:
    enabled: true
    hostPath: /mnt/downloads
  db:
    enabled: true
    size: 1Gi
    accessModes: ReadWriteOnce
    storageClassname: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 0

securityContext:
  capabilities: {}
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

service:
  type: ClusterIP
  port: 6500

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: rdt-client.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: rdt-client-tls-cert
  #    hosts:
  #      - rdt-client.example.com

resources:
  requests:
    cpu: 10m
    memory: 90M
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}
