---
apiVersion: v2
name: generic
description: A Helm chart for generic applications
type: application
kubeVersion: ">=1.22.0-0"
version: 0.5.0
appVersion: ""
keywords:
  - generic
home: https://github.com/tibuntu/helm-charts/tree/main/charts/generic
dependencies: []
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: add additionalPersistentVolumeClaims for creating and mounting extra PVCs
    - kind: added
      description: add additionalVolumes and additionalVolumeMounts for arbitrary volume types
