---
replicaCount: 1

image:
  registry: ~
  repository: ~
  pullPolicy: IfNotPresent
  tag: latest

# -- Set custom environment variables
environment: {}
  # - name: MY_ENV_VAR
  #   value: "my_value"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 911

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 911
  runAsGroup: 911

livenessProbe:
  enabled: false
  initialDelaySeconds: 10
  port: 8080
  path: /

readinessProbe:
  enabled: false
  initialDelaySeconds: 10
  port: 8080
  path: /

service:
  type: ClusterIP
  port: 5314

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-subdomain.my-domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests: {}
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Persistence configuration
persistence:
  # Enable persistence
  enabled: false

  # Name of the PVC. If not set, will be generated as {release-name}-pvc
  name: ""

  # Storage size for the PVC
  size: "1Gi"

  # Access mode for the PVC (ReadWriteOnce, ReadOnlyMany, or ReadWriteMany)
  accessMode: "ReadWriteOnce"

  # Storage class name. If not set, will use the default storage class
  storageClass: ""

  # Mount path for the PVC in the container (default: /data)
  mountPath: "/data"
