---
replicaCount: 1

image:
  registry: ~
  repository: ~
  pullPolicy: IfNotPresent
  tag: latest

# -- Set custom environment variables
environment: {}
  # -- Enable if you want to set custom Lemmy servers, see: https://github.com/aeharding/generic#environment-variables
  # - name: MY_ENV_VAR
  #   value: "my_value"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 911

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 911
  runAsGroup: 911

livenessProbe:
  enabled: false
  port: 8080
  path: /

readinessProbe:
  enabled: false
  port: 8080
  path: /

service:
  type: ClusterIP
  port: 5314

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-subdomain.my-domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 15m
    memory: 50M
  limits:
    cpu: 200m
    memory: 350M

nodeSelector: {}

tolerations: []

affinity: {}
