apiVersion: v2
name: voyager
description: A Helm chart for Voyager
type: application
version: 1.2.0
appVersion: latest
kubeVersion: ">=1.22.0-0"
keywords:
  - voyager
home: https://github.com/tibuntu/helm-charts/tree/main/charts/voyager
sources:
  - https://github.com/aeharding/voyager
dependencies: []
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: add extraEmptyDirs support for writable volume mounts
    - kind: changed
      description: require Kubernetes >= 1.22, drop legacy ingress API versions
