replicaCount: 1

image:
  registry: ghcr.io
  repository: aeharding/voyager
  pullPolicy: IfNotPresent
  tag: latest

# -- Set custom environment variables
environment: {}
  # -- Enable if you want to set custom Lemmy servers, see: https://github.com/aeharding/voyager#environment-variables
  # - name: CUSTOM_LEMMY_SERVERS
  #   value: "lemmy.world,lemmy.ml,sh.itjust.works"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 911

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 911
  runAsGroup: 911

service:
  type: ClusterIP
  port: 5314

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: voyager.my-domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 10m
    memory: 50M
  limits:
    cpu: 50m
    memory: 150M

nodeSelector: {}

tolerations: []

affinity: {}
