replicaCount: 1

image:
  registry: ghcr.io
  repository: tibuntu/kubernetes-node-shutdown
  pullPolicy: IfNotPresent
  tag: v0.1.0

# -- Set custom environment variables
environment:
  - name: NODE_NAME
    value: ""
  - name: SSH_PRIVATE_KEY_PATH
    value: ""
  - name: SSH_HOST
    value: ""
  - name: SSH_USER_NAME
    value: ""
  - name: CPU_THRESHOLD
    value: ""
  - name: MEMORY_THRESHOLD
    value: ""
  - name: SHUTDOWN_DELAY_MINUTES
    value: ""

secret:
  # -- Base64 encoded private key content
  private_key: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 0

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 15m
    memory: 20M
  limits:
    cpu: 200m
    memory: 50M

nodeSelector: {}

tolerations: []

affinity: {}
